# SPDX-FileCopyrightText: 2025 Pier-Hugues Pellerin <ph@heykimo.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Build and deploy
run-name: Build and deploy
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Guix cache
        uses: actions/cache/restore@v3
        with:
          path: ~/.cache/guix
          # use a key that (almost) never matches
          key: guix-cache-${{ github.sha }}
          restore-keys: |
            guix-cache-

      - name: Install Guix
        uses: PromyLOPh/guix-install-action@v1
        with:
          pullAfterInstall: false

      - uses: actions/cache/save@v3
        if: always()
        with:
          path: ~/.cache/guix
          key: guix-cache-${{ github.sha }}

      - name: Ensure no locale warning
        run: test -z "$(guix --version 2>&1 >/dev/null)"

      - name: whereami
        run: guix describe

      - name: haunt build
        run: guix shell -m manifest.scm -- haunt build

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
            SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
            ARGS: "-rlgoDzvc -i --delete"
            SOURCE: "site/"
            REMOTE_HOST: ${{ secrets.HOST }}
            REMOTE_USER: ${{ secrets.USER }}
            TARGET: "/var/www/supervoid.org/"
